name: ZeRO
dependencies:
  - python=3.6
  - jupyterlab
  - pytorch
  - pip:
    - deepspeed
    - git+https://github.com/huggingface/transformers.git
    - datasets
    - pytorch_lightning
    - torchvision
    - pynvml
